names = [
   "Dick Dale",
   "John Abraham",
   "Mark Wahlberg",
   "Donnie Darko",
   "Mike Oxlong",
   "Jeremy Lin",
   "Peso Pluma",
   "Mike Bibby",
   "Ceelo Green",
   "Jermaine Cole",
   "Bobby Boucher",
   "Nathan Brackett",
   "Spencer Shay",
   "Dan Fouts",
   "Genghis Khan",
   "Jimmy Page",
   "Jimmy Neutron",
   "Harry Potter",
   "King David",
   "Jesus Christ",
   "Barack Obama",
   "William Shakespeare",
   "Dante",
   "Henry David Thoreau",
   "Pele"
]